#!/bin/bash -e

POSITIONAL=()
TARGET=${1%/}
UPLOAD_TYPE=""
DESTINATION=""
TMPDIR="/tmp"
ACCESS_TOKEN=""

function archive () {
    mkdir -p "$2/salvare"
    tar -zcvf "$2/salvare/$3.tar.gz" $1 > /dev/null 2>&1
}

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
    cat << EOF
Usage: salvare [TARGET] [OPTIONS]...

Target:
  Backup target

Options:
  -h, --help  Show this message and exit.
  -u, --upload-type [ENUM]  Select upload type [GCS, S3, Dropbox].
  -d, --destination [TEXT]  Destination path by upload type.
  -t, --tmpdir [TEXT]  The path used for writing with temporary.
  -n, --name [TEXT]  Used for the temporary file.
  -a, --access-token [TEXT]  Access token by upload type.
EOF
    exit 0
    ;;
    -u|--upload-type)
    UPLOAD_TYPE="$2"
    shift
    shift
    ;;
    -d|--destination)
    DESTINATION="$2"
    shift
    shift
    ;;
    -t|--tmpdir)
    TMPDIR=${2%/}
    shift
    shift
    ;;
    -n|--name)
    NAME=$2
    shift
    shift
    ;;
    -a|--access-token)
    ACCESS_TOKEN=$2
    shift
    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}"

if [ "${TARGET##*/}" = "." ] || [ "${TARGET##*/}" = ".." ] ; then
    NAME="salvare"
else
    NAME=${TARGET##*/}
fi

if [[ "$TARGET" = "" ]] || [[ "$TARGET" == -* ]]; then
  echo "Required source"
  exit 1
fi

if [ ! -e $TARGET ]; then
  echo "Not found target file or directory. [$TARGET]"
  exit 1
fi

if [[ "$DESTINATION" = "" ]]; then
  echo "Required destination"
  exit 1
fi

if [ ! -e $TMPDIR ]; then
  echo "Not found.tmp directory [$TMPDIR]"
  exit 1
fi

archive $TARGET $TMPDIR $NAME

case $UPLOAD_TYPE in
    GCS)
    GSPATH=${DESTINATION##*gs://}
    BUCKET=${GSPATH%%/*}
    OBJECT=${GSPATH#*/}
    curl -X POST --data-binary @$TMPDIR/salvare/$NAME.tar.gz \
    -H "Authorization: Bearer `gcloud auth print-access-token`" \
    -H "Content-Type: application/gzip" \
    "https://storage.googleapis.com/upload/storage/v1/b/$BUCKET/o?uploadType=media&name=$OBJECT"
    rm -f $TMPDIR/salvare/$NAME.tar.gz
    ;;
    S3)
    ;;
    Dropbox)
    curl -X POST --data-binary @$TMPDIR/salvare/$NAME.tar.gz \
        -H "Authorization: Bearer $ACCESS_TOKEN" \
        -H "Dropbox-API-Arg: {\"path\": \"$DESTINATION\"}" \
        -H "Content-Type: application/octet-stream" \
        "https://content.dropboxapi.com/2/files/upload"
    ;;
    *)
    echo "Required upload_type is in [GCS, S3, Dropbox]"
    exit 1
    ;;
esac
